export const data = {
  "UrisHall": [
    [
      null,
      "Walk away from the door until you see the staircase on your left.",
      null,
      "Turn and walk to the end of the hall. Turn right and the exit is on your left.",
      null,
      null
    ],
    [
      "Turn right and walk to the end of the hallway.",
      null,
      "Enter the staircase.",
      null,
      null,
      null
    ],
    [
      null,
      "Exit the staircase.",
      null,
      null,
      "Go up one flight.",
      null
    ],
    [
      "Enter Uris Hall. Make a right turn. Walk to the end of the hall. Make a left turn. Walk to the end of the hall.",
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      "Go down one flight.",
      null,
      "Exit the building straight out of the staircase."
    ],
    [
      null,
      null,
      null,
      null,
      "Walk straight to the down staircase."
    ]
  ],
  "Statler": [
    [
      null,
      "Walk forward to the bottom of the stairs",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      "Walk forward - the exit is directly in front of you.",
      null,
      null,
      "Go up the stairs",
      null,
      null,
      null,
      "Go up the stairs",
      "Go straight past the stairs away from the doors. Take a left through the" +
      " double glass doors and continue past Mac's Cafe and the hotel laundry, " +
      "taking a left at the single wooden door. Take an immediate right away from " +
      "Terrace, and exit through the Terrace main entrance."
    ],
    [
      null,
      null,
      null,
      "Turn right. Walk past the curved bench towards the Statler Auditorium. ",
      "After entering, make a left, and walk straight. Exit immediately to the left of the atrium",
      null,
      null,
      null,
      null
    ],
    [
      null,
      "Go down the stairs.",
      "Go away from the staircase past the curved bench. Make a left. The exit will be on your right.",
      null,
      "Walk away from the staircase past the curved bench. The exit is immediately to the left of the atrium. ",
      null,
      null,
      "Walk past the staircase towards the edge of the balcony. ",
      null
    ],
    [
      null,
      null,
      "After entering, walk straight until you see an exit on your left. ",
      "Make a left and walk past the curved bench towards the Statler Auditorium. ",
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      "Enter the staircase. Go down one flight and exit the building. ",
      "Walk away from the staircase towards the balcony. ",
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      "Make an immediate right and go up one flight of stairs. Exit the staircase. ",
      null,
      null,
      null
    ],
    [
      null,
      "Go down the stairs. ",
      null,
      "Walk away from the balcony towards the Statler Auditorium. ",
      null,
      "Make a left when facing the balcony and walk straight until you see a staircase. ",
      null,
      null,
      null
    ],
    [
      null,
      "Walk in through Terrace main entrance. Turn left at the elevator. Go through single wooden " +
      "door and make an immediate right. Continue down the hallway, past hotel laundry and Mac's Cafe " +
      "until you reach the bottom of the staircase. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  ],
  "Duffield": [
    [
      null, null, null, null, null, null, null, null, null, null,
      "Walk straight to the vending machines. ",
      null, null, null, null, null, null, null, null, null
    ],
    [
      null, null,
      "Make an immediate right and enter the Center For Nanoscale Fabrication. Continue straight along the red wall with orange windows. Proceed into the stairwell and exit. ",
      null, null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Make an immediate right and enter the Center For Nanoscale Fabrication. Continue straight along the red wall with orange windows, making a left at the lockers. When you reach the end of the hallway, make a right, then left through double glass doors into the Duffield Atrium. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      "Go straight out of the stairwell. Make a left out of the staircase and make a right at the windows. Continue down the long hallway, until you reach double doors straight ahead. Proceed through, and exit on your left. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Make a right out of the stairwell. When you reach the end of the hallway, make a right, then left through double glass doors into the Duffield Atrium. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go down the stairs and enter the Duffield Atrium. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      "Enter Phillips Hall. Proceed straight until you see the red motorcycle. Make a left at the motorcycle. Continue straight until a staircase is on your right. Go down one flight. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Continue straight until you see a red motorcycle. Make a left, followed by a sharp right, continuing in the same direction. At the end of the hall, go through the door with a sign to Upson. Once through the door, make an immediate right, proceeding through another wooden door. Make a left, and go down the ramp, and enter Upson hall. Once you are in Upson hall, make a left through the grey double doors, and continue until the hallway turns right. Follow the signs towards Grumman and Rhodes hall. Once you enter the Theory Center, follow the signs for CIS Professional Masters. Exit on your left. "
    ],
    [
      null,
      null,
      null,
      null,
      null,
      "Go up one flight of stairs. Take a left. At the end of the hallway make a right, and exit at the end of the next hallway. ",
      null,
      "At the bottom of the staircase make a right. ",
      null,
      null,
      "At the bottom of the stairs, make a left out of the staircase. Go straight, then make a left at the vending machines. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go up one flight of stairs. Turn right, and continue until you see a red motorcycle. Make a left. At the end of the hall, go through the door with a sign to Upson. Once through the door, make an immediate right, proceeding through another wooden door. Make a left, and go down the ramp, and enter Upson hall. Once you are in Upson hall, make a left through the grey double doors, and continue until the hallway turns right. Follow the signs towards Grumman and Rhodes hall. Once you enter the Theory Center, follow the signs for CIS Professional Masters. Exit on your left. "
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      "Go towards the elevator. Enter the staircase on your left. ",
      null,
      "Walking away from the elevator, the exit will be on your right. ",
      "Walking away from the elevator, the exit is straight ahead. ",
      "Walk towards the elevator and make a left at the vending machines. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Walk to the intersection of the hallways. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      "Walk away from the atrium. The exit is straight ahead. ",
      null,
      null,
      null,
      null,
      null,
      "Walk towards the elevator. Make a right. The staircase will be on your right. Go up one flight. ",
      "Walk towards the elevator. Make a right. The staricase will be on your right. ",
      null,
      null,
      null,
      "Go into the atrium. ",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      "Go towards the Center for Nanoscale Fabrication. Go through the glass double doors. Make a right immediately after, then a left at the end of the hall. Walk past the lockers, and take at the end of the hall. Walk to the end of the hall with the red wall on your right. Go through the double doors, and the exit is on your left. ",
      "Go towards the Center for Nanoscale Fabrication. Go through the glass double doors. Make a right immediately after, then a left at the end of the hall. Turn left into the stairwell and exit. ",
      "Exit under the sign Engineering Quadrangle. ",
      "Go up the stairs opposite the entrance to Upson. The exit is at the top of the stairs. ",
      null,
      null,
      null,
      null,
      null,
      "Go towards the vending machines to the left of Mattin's Cafe. ",
      null,
      "Exit under the Hoy Road sign. ",
      "Enter Upson Hall through the set of several double doors. ",
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go through the grey doors to enter the Duffield Atrium. ",
      null,
      null,
      "Walk towards the giant pendulum. The exit will be on your right. ",
      "Walk past the giant pendulum and down the stairs. The exit is straight ahead. ",
      "Walk away from the giant pendulum (a left out of Duffield). ",
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go left. ",
      null,
      "Go right and down the stairs. The exit is straight ahead. ",
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go up the stairs and down the hallway. ",
      "Go up the stairs. The exit is to your left. ",
      null,
      null,
      null,
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Go away from the doors. ",
      null,
      null,
      null,
      "Walk away from the seating area. Follow the hallway until you reach the grey double doors and go through. ",
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "The exit is on your left. ",
      "Go up the S staircase 1 flight. Go right. Follow the signs to Grumman/Rhodes Hall. Once your reach the Theory Center, follow signs for CIS Professional Masters. The exit will be on your left. "
    ],
    [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "",
      null,
      null
    ],
    [
      null,
      null,
      null,
      null,
      null,
      "Enter Rhodes Hall. Take a right. At the end of the hall, take a right, following signs for Grumman/Upson Hall. Enter the double doors to go to Upson. Continue straight down the Upson hallway until you reach a set of grey double doors. Proceed through and up the ramp, then take a right at the top. Go through the door labeled Phillips Hall. Make a left at the end of the hall. Proceed to the end of the hall. Make a left. Make an immediate right. Proceed to the exit straight ahead at the end of the hall. ",
      "Enter Rhodes Hall. Take a right. At the end of the hall, take a right, following signs for Grumman/Upson Hall. Enter the double doors to go to Upson. Continue straight down the Upson hallway until you reach a set of grey double doors. Proceed through and up the ramp, then take a right at the top. Go through the door labeled Phillips Hall. Make a left at the end of the hall. Proceed to the end of the hall. Make a right, and take the staircase on your right, down one flight. ", ,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "Enter Rhodes Hall. Take a right. At the end of the hall, take a right, following signs for Grumman/Upson. Before the double doors, take the S staircase 1 flight down. Exit the staircase to the left. ",
      null,
      null
    ]
  ]
}

export const latlongToIndex = {
  "UrisHall": {
    "42.44739113622921,-76.48193314453428": 0,
    "42.44700992562832,-76.48221781037817": 3,
    "42.44742622033418,-76.48220070314869": 5
  },
  "Statler": {
    "42.44670545033039,-76.48207251253336": 8,
    "42.445623262398286,-76.48168337091782": 4,
    "42.44576361346584,-76.48162980916125": 2,
    "42.445281620850025,-76.48218639444269": 6,
    "42.44562353717044,-76.48242370006373": 0
  },
  "Duffield": {
    "42.445003621053395,-76.48238232724367": 4,
    "42.444902868782734,-76.48292944695994": 1,
    "42.44441567672523,-76.48279201104828": 2,
    "42.444390048568074,-76.4827731991422": 3,
    "42.44449196425085,-76.48190850370958": 0,
    "42.44452709657613,-76.48188503438222": 8,
    "42.444608968177036,-76.48162390067553": 9,
    "42.445050127769775,-76.48225666354386": 5,
    "42.44401293742597,-76.4829223613867": 15,
    "42.44406388601698,-76.48252490164128": 14,
    "42.444166518123694,-76.48220322942626": 11,
    "42.444037722212414,-76.48187469404823": 16,
    "42.443544079159324,-76.48188813502219": 18,
    "42.44356665572746,-76.48134816944994": 19
  }
}